void Delay100ms(int count);
void newplat_init(void);
void print_plat(void);
void task_down(void);
void scoring(void);
void start(void);
void pl_move(void);
void pl_jump(void);
void Screen1 (uint32_t userinput);
int pl_y(void);
void check_plat(void);
